import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers/Providers";
import Header from "@/components/shared/Header";
import Container from "@/components/shared/Container";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[url('/org.jpg')] dark:bg-[url('/dr.jpg')] bg-cover bg-center min-h-screen`}
      >
        <Providers>
          <Container className="py-[50px]">
            <div className=" bg-white/30 dark:bg-black/30 backdrop-blur-md border border-white/20 shadow-lg rounded-xl min-h-[calc(100dvh-100px)] px-10 py-5">
              <Header />

              {children}
              <Footer />
            </div>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
